Document: statusengine
Title: Debian statusengine Manual
Author: <insert document author here>
Abstract: This manual describes what statusengine is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/statusengine/statusengine.sgml.gz

Format: postscript
Files: /usr/share/doc/statusengine/statusengine.ps.gz

Format: text
Files: /usr/share/doc/statusengine/statusengine.text.gz

Format: HTML
Index: /usr/share/doc/statusengine/html/index.html
Files: /usr/share/doc/statusengine/html/*.html
